# Generated by Django 5.2 on 2025-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='victim',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
