# Generated by Django 5.2 on 2025-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0002_remove_victim_timestamp_victim_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='motivational_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
