# Generated by Django 5.2 on 2025-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phish', '0003_victim_age_victim_motivational_letter_victim_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
